### ISSUE TITLE
Titles for action buttons do not line up at the bottom of LE

### ISSUE THREAD

**Issue by jeepurs** [learningequality/learningequality.org#355]
Jobs and Internships clickable buttons are not in line with the others.

![image](https://user-images.githubusercontent.com/5150483/33747811-f1855842-db79-11e7-97f2-36b7e553890a.png)

**Comment by indirectlylit** [comment]
This was supposed to be addressed in this commit: https://github.com/learningequality/learningequality.org/pull/353/commits/108aa5318de5f71d467369749152eb01784fd869

Need to debug why those styles aren't being applied.

**Comment by indirectlylit** [comment]
I believe it was a caching issue because [things look fine for me](http://learningequality.org/) now:

![image](https://user-images.githubusercontent.com/2367265/33909216-bd162964-df3f-11e7-9ccb-951bfc51d632.png)

@jamalex also decreased the amount of caching imposed so hopefully this kind of issue can be avoided in the future...
